## check for OS
string (REGEX MATCH "Darwin" MAC "${CMAKE_SYSTEM_NAME}${CMAKE_HOST_SYSTEM_NAME}")
string (REGEX MATCH "Linux" LINUX "${CMAKE_SYSTEM_NAME}${CMAKE_HOST_SYSTEM_NAME}")
set (WIN ${WIN32})
